# Generated by Django 2.2.6 on 2023-12-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='character',
            field=models.CharField(default='all', max_length=30),
            preserve_default=False,
        ),
    ]
