# Generated by Django 5.0 on 2023-12-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isUber',
            field=models.BooleanField(default=False),
        ),
    ]
